name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo ${{ vars.testOne }}
